### PR TITLE
Add blacklist to masks

### LINKED ISSUE #8: NOT mask?
It'd be nice to have the ability to use json-mask to say what fields should NOT be returned.  For instance, if I have some JSON where every field except one should be included.

Is this possible currently?  I didn't see anything in the API docs for it.

### PR DESCRIPTION
**Pull request by pedrobranco**
This PR adds a blacklist feature to a mask.

Closes #8.

### CODE REVIEW

**Comment by nemtsov** [comment]
Awesome!
One concern: how do you deal with only selecting the `-world` key-value pair here: `{ "hello": "one", "-world": "two" }`

**Comment by pedrobranco** [comment]
> One concern: how do you deal with only selecting the -world key-value pair here: { "hello": "one", "-world": "two" }?

The main reason I've sticked to `-` is because is not a very common practice to name a JSON property prefixed with `-`. 

To fix that particular issue we can escape any blacklist rule if matches any object key, just like in the case when the object has the properties `{ foo: 1, '-foo': 2 }` and a mask to select `-foo` (fair trade-off since the `json-mask` in mostly for selecting properties).

@nemtsov WDYT?

**Comment by pedrobranco** [comment]
This solution @nemtsov looks good to you?

**Comment by nemtsov** [comment]
I think supporting NOT is a language feature; specifically it’s an addition to the grammar and needs to be done on the compiler. 

I’m also used to `!` representing NOT, as that’s what’s used in many languages.

**Comment by pedrobranco** [comment]
> I think supporting NOT is a language feature; specifically it’s an addition to the grammar and needs to be done on the compiler.

IMHO,  `!` is a filter just like `*`, so I don't see the purpose of specifying it on the compiler. 

> I’m also used to ! representing NOT, as that’s what’s used in many languages.

I'm also used to it, so +1 for `!`.

**Comment by nemtsov** [comment]
I understand your reasoning, but I’m not certain it was right to implement the `*` in the filter in the first place. Why should it live in the filter and not be compiled?

**Pull request closed without merging**
